#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get -y install haproxy=1.8.\*
sed -i '/errorfile 504/a listen claudettekeira' /etc/haproxy/haproxy.cfg
sed -i '/listen rhysmurage/a         bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a         mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a         server 136966-web-01 52.201.32.180:80 check' /etc/haproxy/haproxy.cfg
sed -i '/server 136966-web-01 52.201.32.180:80 check/a         server 136966-web-02 54.158.180.61:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
